vim:fileencoding=utf-8:foldmethod=marker

#BEGIN_THEME
include ./theme.conf
#END_THEME

## Init with login shell to pick up env etc.
shell zsh --login

## enable scripting
allow_remote_control yes

#: Listen to the specified socket for remote control connections. Note
#: that this will apply to all kitty instances. It can be overridden
#: by the kitty --listen-on command line option. For UNIX sockets,
#: such as unix:${TEMP}/mykitty or unix:@mykitty (on Linux).
#: Environment variables are expanded and relative paths are resolved
#: with respect to the temporary directory. If {kitty_pid} is present,
#: then it is replaced by the PID of the kitty process, otherwise the
#: PID of the kitty process is appended to the value, with a hyphen.
#: For TCP sockets such as tcp:localhost:0 a random port is always
#: used even if a non-zero port number is specified.  See the help for
#: kitty --listen-on for more details. Note that this will be ignored
#: unless allow_remote_control is set to either: yes, socket or
#: socket-only. Changing this option by reloading the config is not
#: supported.
listen_on unix:/tmp/kitty

#: Allow other programs to control kitty. If you turn this on, other
#: programs can control all aspects of kitty, including sending text
#: to kitty windows, opening new windows, closing windows, reading the
#: content of windows, etc. Note that this even works over SSH
#: connections. The default setting of no prevents any form of remote
#: control. The meaning of the various values are:

term xterm-kitty

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

modify_font cell_height 120%

disable_ligatures tab cursor
# END_KITTY_FONTS

cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0
cursor_stop_blinking_after 0

cursor_trail 1
cursor_trail_decay 0.01 0.5
cursor_trail_start_threshold 0

background_opacity 0.9
background_blur 5
dynamic_background_opacity yes

editor nvim

hide_window_decorations titlebar-only

# BEGIN TAB_BAR_STYLES
tab_title_template "{session_name or tab.active_wd.rsplit('/', 1)[-1]}"
tab_bar_style powerline
tab_bar_edge top
# END_TAB_BAR_STYLES
#
macos_show_window_title_in none
macos_titlebar_color #292522
macos_menubar_title_max_length 0
window_padding_width 10

enabled_layouts splits,stack,tall,*

startup_session ~/git/dotfiles/.config/kitty/sessions/home.kitty-session


action_alias launch_session_select launch --type=overlay /bin/zsh -c "$HOME/github/dotfiles-latest/kitty/scripts/kitty-list-sessions.sh"
map ctrl+b>s launch_session_select
