foreground #605A52
background #FCFBF9

selection_background #F7F3EE
selection_foreground #605A52

cursor #605A52
cursor_text_color #FCFBF9

url_color #556995

color0 #282422
color1 #8F5652
color2 #747B4D
color3 #886A44
color4 #556995
color5 #83577D
color6 #477A7B
color7 #605A52

color8  #7D7874
color9  #A86C67
color10 #9AA06A
color11 #A07B51
color12 #7286A4
color13 #A2809A
color14 #6EA1A3
color15 #FCFBF9

active_tab_background   #F7F3EE
inactive_tab_background #FCFBF9
active_tab_foreground   #605A52
inactive_tab_foreground #605A52
tab_bar_background      #F7F3EE
