"$schema" = 'https://starship.rs/config-schema.json'


format = "$all"

right_format = """$time"""

palette = 'lava'

[time]
disabled = false
style = "bold fg:orange "
format = "[󱑎 $time]($style)"

# https://github.com/sharkdp/vivid/blob/master/themes/lava.yml
[palettes.lava]
base1 = "#b3608"
base0 = "#839496"
base2 = "#eee8d5"
yellow = "#b58900"
background_color = "#1a1a1a"
black = "#000000"
orange = "#e06206"
darkorange = "#FF9400"
amber = "#FFC100"
vermilion = "#FF4B00"
alpine = "#BF9C30"
christine = "#BF5B30"
fire = "#A63000"
kourkinova = "#BF5B30"
chardonnay = "#FFC373"
