
# set 1-based index for tab names
set -g base-index 1
set -g pane-base-index 1

# status bar
set -g status-position top
set -g status-style bg=default,fg=white,bright
set -g status-left ""
set -g status-right "#[reverse]#S#[noreverse]"
set -g window-status-format "#[fg=white,bright]#I #[fg=default]\
#{?#{==:#{window_index,1},,}"
set -g window-status-current-format "#{?#{!=:#{window_index, 1}},#[reverse],}\
#[noreverse] #I \
#[reverse]"

set -g window-status-bell-style "bg=red,nobold"
set -g window-status-current-style \
"#{?window-zoomed_flag,bg=yellow, bg=magenta,fg=black,nobold}"

set -g renumber-windows on

# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX}
set -g status-bg red
%endif

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-features ",xterm*:RGB"

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"


# Rebind prefix
set -g prefix `
unbind C-b
bind ` send-prefix

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

# A key to toggle between smallest and largest sizes if a window is visible in
# multiple places
bind F set -w window-size

# Keys to toggle monitoring activity in a window and the synchronize-panes option
bind m set monitor-activity
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

bind - split-window -v 
bind | split-window -h
#### POPUPS

#open lazygit in the current panes path
unbind C-g
bind C-g display-popup -h 80% \
-w 80% \
-d '#{pane_current_path}' \
-E "bash ~/.config/tmux/scripts/run-lazygit.sh"

# launch claude in cwd of focused pane
unbind C-c
bind C-c display-popup -h 80% \
-w 80% \
-d '#{pane_current_path}' \
-E "claude code"

### END POPUPS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
